name: background_remover
description: Flutter package that remove background of a selfie with advanced editing capabilities
version: 0.0.4
repository: https://github.com/Antoinegtir/background-remover
homepage: https://github.com/Antoinegtir/background-remover

environment:
  sdk: '>=3.6.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.2
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_object_detection: ^0.14.0
  image_picker: ^1.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  plugin:
    platforms:
      android:
        package: com.example.background_remover
        pluginClass: Package
